export const hacketRankCookie = [
    {
        "domain": ".hackerrank.com",
        "expirationDate": 1754335240,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_biz_flagsA",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "%7B%22Version%22%3A1%2C%22ViewThrough%22%3A%221%22%2C%22XDomain%22%3A%221%22%7D",
        "id": 1
    },
    {
        "domain": ".hackerrank.com",
        "expirationDate": 1754335281,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_biz_nA",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "4",
        "id": 2
    },
    {
        "domain": ".hackerrank.com",
        "expirationDate": 1754335281,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_biz_pendingA",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "%5B%5D",
        "id": 3
    },
    {
        "domain": ".hackerrank.com",
        "expirationDate": 1754335277,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_biz_uid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "2f95e0c5ef574ad6aa790d78bd7ad0cd",
        "id": 4
    },
    {
        "domain": ".hackerrank.com",
        "expirationDate": 1722883168,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ce.clock_data",
        "path": "/",
        "sameSite": "strict",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "-8%2C49.37.132.92%2C1%2C6a23775729fd6c068d20d383cbe27f9b%2CChrome%2CIN",
        "id": 5
    },
    {
        "domain": ".hackerrank.com",
        "expirationDate": 1722883168,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ce.clock_event",
        "path": "/",
        "sameSite": "strict",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1",
        "id": 6
    },
    {
        "domain": ".hackerrank.com",
        "expirationDate": 1754332774,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ce.s",
        "path": "/",
        "sameSite": "strict",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "v~067312bf6dce687fb54c3fcb45cdbd0cc2ff506e~lcw~1722796773029~lva~1722796768420~vpv~0~v11.cs~411501~v11.s~e1996730-5290-11ef-9b33-b58395dac5b9~v11.sla~1722796774801~gtrk.la~lzfwptmt~v11.send~1722796773029~lcw~1722796774801",
        "id": 7
    },
    {
        "domain": ".hackerrank.com",
        "expirationDate": 1757356769,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_fcdscv",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "eyJDdXN0b21lcklkIjoiOWUyMDZiMGQtMDAxNC00MmI5LThkMzktYzJiOTA5NGEyNzMxIiwiVmlzaXRvciI6eyJFbWFpbCI6bnVsbCwiRXh0ZXJuYWxWaXNpdG9ySWQiOiJlMWNiN2VlYi03MTJhLTQ3ZTQtOTIyYy0yYTJlMTQzYTZiMzQifSwiVmlzaXRzIjpbXSwiQWN0aXZpdGllcyI6W10sIkRpYWdub3N0aWNNZXNzYWdlIjpudWxsfQ==",
        "id": 8
    },
    {
        "domain": ".hackerrank.com",
        "expirationDate": 1757356770,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GA1.1.228833128.1722796769",
        "id": 9
    },
    {
        "domain": ".hackerrank.com",
        "expirationDate": 1757356774,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_0QME21KCCM",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GS1.1.1722796768.1.1.1722796774.54.0.0",
        "id": 10
    },
    {
        "domain": ".hackerrank.com",
        "expirationDate": 1757356774,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_BCP376TP8D",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GS1.1.1722796768.1.1.1722796774.0.0.0",
        "id": 11
    },
    {
        "domain": ".hackerrank.com",
        "expirationDate": 1757356774,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_R0S46VQSNQ",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GS1.1.1722796768.1.1.1722796774.54.0.0",
        "id": 12
    },
    {
        "domain": ".hackerrank.com",
        "expirationDate": 1757356774,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_X2HP4BPSD7",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GS1.1.1722796768.1.1.1722796774.0.0.0",
        "id": 13
    },
    {
        "domain": ".hackerrank.com",
        "expirationDate": 1730572769,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gcl_au",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1.1.1206572666.1722796769",
        "id": 14
    },
    {
        "domain": ".hackerrank.com",
        "expirationDate": 1757356770,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_mkto_trk",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "id:487-WAY-049&token:_mch-hackerrank.com-1722796770914-34405",
        "id": 15
    },
    {
        "domain": ".hackerrank.com",
        "expirationDate": 1754332791,
        "hostOnly": false,
        "httpOnly": false,
        "name": "hackerrank_mixpanel_token",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "b4fc87ff-e537-4de7-bf14-9baa9e6b3712",
        "id": 16
    },
    {
        "domain": ".hackerrank.com",
        "expirationDate": 1757356824,
        "hostOnly": false,
        "httpOnly": false,
        "name": "user_theme",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "light",
        "id": 17
    },
    {
        "domain": ".hackerrank.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "user_type",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "hacker",
        "id": 18
    },
    {
        "domain": ".www.hackerrank.com",
        "expirationDate": 1754332771,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_zitok",
        "path": "/",
        "sameSite": "strict",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "d76811938a17cc61c6f51722796769",
        "id": 19
    },
    {
        "domain": "www.hackerrank.com",
        "hostOnly": true,
        "httpOnly": true,
        "name": "_hrank_session",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "82c058635286163c1e50bd3906300645",
        "id": 20
    },
    {
        "domain": "www.hackerrank.com",
        "hostOnly": true,
        "httpOnly": false,
        "name": "hrc_l_i",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "T",
        "id": 21
    },
    {
        "domain": "www.hackerrank.com",
        "expirationDate": 1722883190,
        "hostOnly": true,
        "httpOnly": false,
        "name": "metrics_user_identifier",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "bda423-fb460a66e02da4f5482b2d0f6da29e2cd63dff06",
        "id": 22
    },
    {
        "domain": "www.hackerrank.com",
        "expirationDate": 1723401591,
        "hostOnly": true,
        "httpOnly": false,
        "name": "react_var",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "false__cnt4",
        "id": 23
    },
    {
        "domain": "www.hackerrank.com",
        "expirationDate": 1723401591,
        "hostOnly": true,
        "httpOnly": false,
        "name": "react_var2",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "false__cnt4",
        "id": 24
    },
    {
        "domain": "www.hackerrank.com",
        "expirationDate": 1754332768,
        "hostOnly": true,
        "httpOnly": false,
        "name": "referrer",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "https://www.google.com/",
        "id": 25
    },
    {
        "domain": "www.hackerrank.com",
        "expirationDate": 1724006390,
        "hostOnly": true,
        "httpOnly": true,
        "name": "remember_hacker_token",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaGJDRnNHYVFNanBMMGlJaVF5WVNReE1DUjJVa0pxWVhvNU1FeFZaR1l6TDA5dlJVWk9kazFsU1NJWE1UY3lNamM1TmpjNU1DNDNNems0TURrekJqb0dSVVk9IiwiZXhwIjoiMjAyNC0wOC0xOFQxODozOTo1MC43MzlaIiwicHVyIjpudWxsfX0%3D--aad7870aa6f4cf0462c0c76d21cb15844b978357",
        "id": 26
    },
    {
        "domain": "www.hackerrank.com",
        "expirationDate": 1722838348,
        "hostOnly": true,
        "httpOnly": false,
        "name": "session_id",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "ohlmgr3u-1722799239344",
        "id": 27
    }
]